### ISSUE TITLE
rsc's Havlak code from 2011? 26 -> 2 seconds

### ISSUE THREAD

**Issue by createconnect** [kostya/benchmarks#216]
This is a wonderful find and Halvak is the longest code and I don't understand what it does.

Was the code in:
https://github.com/kostya/benchmarks/blob/master/havlak/havlak.go

Based on this with modified code?
https://github.com/chandradeepak/benchgraffiti/blob/master/havlak/havlak3.go

I can still compile original code from 2011 on Golang 1.13.5 without any modifications.
**rsc's Havlak (havlak6.go) with pool took:** 2 seconds (87MB memory)
**Kostya's Havlak in this repo took:** 26 seconds (350MB memory)

Russ Cox works on Go language.
https://github.com/chandradeepak/benchgraffiti/tree/master/havlak

Have a great holiday!

**Comment by kostya** [comment]
as it seems, i choose havlak3 code because there was the similar implementations in other languages, havlak6 change the algorithm, so we should write the same for others. Btw this test quite hard to understand, and also to measure what is really doing, maybe we should remove it.

**Comment by createconnect** [comment]
I'm fine since the test is unhelpful for newcomers and I have been mistook Golang for bad performance for so long until I only realise it's biased comparisons. So we can remove it. :)

**Comment by nuald** [comment]
@createconnect Could you please clarify where we have the "biased comparisons"? Surely, the current implementation of the Havlak's loop finder is not the best and can be optimized with pools and other techniques, however in that case the changes should be applied to all languages. If you assume that some implementations have the optimized versions, then could you please point it to us, so we can take care of it. It's difficult to have the consistent reference implementations due to differences in languages, and we could miss it.

CC @kostya A little bit of context here. I'm not sure about the actual origins, but the Havlak's benchmark code came from Google (a mirror here: https://github.com/zchee/multi-language-bench/). You may read the presentation (https://github.com/zchee/multi-language-bench/blob/master/doc/scaladays2011-paper/main.pdf) and find out that the algorithm is described in ”Nesting of reducible and irreducible loops”, by Havlak, Rice University, 1997.

P. S. I'm not sure about removing it as after that the only test that verify the languages (not libraries) would be bf2, and it has some issues (otherwise Kotlin won't be the winner for a small input). While there are some concerns that JIT allows to make the CPU branch predictions better, it still requires some research. Maybe we don't need Havlak's benchmarks per se, but having some good replacement would be nice.

**Comment by nuald** [comment]
Havlak tests have been removed.
